apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-env
spec:
  generators:
  - git:
      repoURL: https://github.com/Anil-YadavK8s/gitops-cert-level-2-examples
      revision: HEAD
      directories:
      - path: ./environment-promotion/envs/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Anil-YadavK8s/gitops-cert-level-2-examples
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
